function g(b){var d=typeof b;if("object"==d)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return d;var c=Object.prototype.toString.call(b);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==d&&"undefined"==typeof b.call)return"object";return d};function h(b,d){var c=Array.prototype.slice.call(arguments),a=c.shift();if("undefined"==typeof a)throw Error("[goog.string.format] Template required");return a.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,e,b,d,f,x,C,D){if("%"==x)return"%";var y=c.shift();if("undefined"==typeof y)throw Error("[goog.string.format] Not enough arguments");arguments[0]=y;return h.b[x].apply(null,arguments)})}h.b={};
h.b.s=function(b,d,c){return isNaN(c)||""==c||b.length>=c?b:b=-1<d.indexOf("-",0)?b+Array(c-b.length+1).join(" "):Array(c-b.length+1).join(" ")+b};
h.b.f=function(b,d,c,a,l){a=b.toString();isNaN(l)||""==l||(a=b.toFixed(l));var e;e=0>b?"-":0<=d.indexOf("+")?"+":0<=d.indexOf(" ")?" ":"";0<=b&&(a=e+a);if(isNaN(c)||a.length>=c)return a;a=isNaN(l)?Math.abs(b).toString():Math.abs(b).toFixed(l);b=c-a.length-e.length;return a=0<=d.indexOf("-",0)?e+a+Array(b+1).join(" "):e+Array(b+1).join(0<=d.indexOf("0",0)?"0":" ")+a};h.b.d=function(b,d,c,a,l,e,r,v){return h.b.f(parseInt(b,10),d,c,a,0,e,r,v)};h.b.i=h.b.d;h.b.u=h.b.d;function k(b){return b}var m=["cljs","core","set_print_fn_BANG_"],n=this;m[0]in n||!n.execScript||n.execScript("var "+m[0]);for(var p;m.length&&(p=m.shift());){var q;if(q=!m.length)q=void 0!==k;q?n[p]=k:n=n[p]?n[p]:n[p]={}}function s(b){var d="string"==typeof b;return d?"\ufdd0"!==b.charAt(0):d}function t(b,d){var c=null==d?null:d.constructor,c=null!=(null!=c&&!1!==c?c.n:c)&&!1!==(null!=c&&!1!==c?c.n:c)?c.p:g(d);return Error(["No protocol method ",b," defined for type ",c,": ",d].join(""))}
var u={},w=function(){function b(a,b,e){if(a?a.g:a)return a.g(a,b,e);var c;c=w[g(null==a?null:a)];if(!c&&(c=w._,!c))throw t("ILookup.-lookup",a);return c.call(null,a,b,e)}function d(a,b){if(a?a.e:a)return a.e(a,b);var e;e=w[g(null==a?null:a)];if(!e&&(e=w._,!e))throw t("ILookup.-lookup",a);return e.call(null,a,b)}var c=null,c=function(a,c,e){switch(arguments.length){case 2:return d.call(this,a,c);case 3:return b.call(this,a,c,e)}throw Error("Invalid arity: "+arguments.length);};c.a=d;c.c=b;return c}(),
z=function(){function b(a,b,e){if(a?a.l:a)return a.l(a,b,e);var c;c=z[g(null==a?null:a)];if(!c&&(c=z._,!c))throw t("IReduce.-reduce",a);return c.call(null,a,b,e)}function d(a,b){if(a?a.k:a)return a.k(a,b);var c;c=z[g(null==a?null:a)];if(!c&&(c=z._,!c))throw t("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(a,c,e){switch(arguments.length){case 2:return d.call(this,a,c);case 3:return b.call(this,a,c,e)}throw Error("Invalid arity: "+arguments.length);};c.a=d;c.c=b;return c}(),A=function(){function b(a,
b,c,d){for(var f=a.length;;)if(d<f)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function d(a,b,c){for(var d=a.length,f=0;;)if(f<d)c=b.a?b.a(c,a[f]):b.call(null,c,a[f]),f+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.h?b.h():b.call(null);for(var d=a[0],f=1;;)if(f<c)d=b.a?b.a(d,a[f]):b.call(null,d,a[f]),f+=1;else return d}var a=null,a=function(a,e,r,v){switch(arguments.length){case 2:return c.call(this,a,e);case 3:return d.call(this,a,e,r);case 4:return b.call(this,
a,e,r,v)}throw Error("Invalid arity: "+arguments.length);};a.a=c;a.c=d;a.o=b;return a}();z.array=function(b,d){return A.a(b,d)};z.array=function(b,d,c){return A.c(b,d,c)};
var B=function(){function b(a,b,c){if(null!=a){var d;d=a?((d=a.m&256)?d:a.j)?!0:!1:!1;a=d?a.g(a,b,c):a instanceof Array?b<a.length?a[b]:c:s(a)?b<a.length?a[b]:c:u[g(null==a?null:a)]||u._?w.c(a,b,c):c}else a=c;return a}function d(a,b){var c;null==a?c=null:(c=a?((c=a.m&256)?c:a.j)?!0:!1:!1,c=c?a.e(a,b):a instanceof Array?b<a.length?a[b]:null:s(a)?b<a.length?a[b]:null:u[g(null==a?null:a)]||u._?w.a(a,b):null);return c}var c=null,c=function(a,c,e){switch(arguments.length){case 2:return d.call(this,a,c);
case 3:return b.call(this,a,c,e)}throw Error("Invalid arity: "+arguments.length);};c.a=d;c.c=b;return c}();String.prototype.call=function(){var b=null;return b=function(b,c,a){switch(arguments.length){case 2:return B.a(c,this.toString());case 3:return B.c(c,this.toString(),a)}throw Error("Invalid arity: "+arguments.length);}}();String.prototype.apply=function(b,d){return b.call.apply(b,[b].concat(d.slice()))};String.prototype.apply=function(b,d){return 2>d.length?B.a(d[0],b):B.c(d[0],b,d[1])};console.log("test aoeuaaaao");console.log("test aoeua1234o");